// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/status.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	// The error code see ecode.Code
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A developer-facing error message, which should be in English. Any
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// A list of messages that carry the error details.  There is a common set of
	// message types for APIs to use.
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f469744098fed031, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "cn.com.ahaschool.status.Status")
}

func init() { proto.RegisterFile("types/status.proto", fileDescriptor_f469744098fed031) }

var fileDescriptor_f469744098fed031 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8d, 0x41, 0xce, 0x82, 0x40,
	0x0c, 0x85, 0xc3, 0xcf, 0x2f, 0xc4, 0x71, 0xd7, 0x98, 0x38, 0xba, 0x22, 0xae, 0x58, 0x95, 0x44,
	0x4f, 0xe0, 0x15, 0xf0, 0x04, 0x65, 0x28, 0x60, 0x02, 0x94, 0xd8, 0x61, 0xc1, 0xed, 0x4d, 0x86,
	0xcc, 0xae, 0x7d, 0xef, 0x7b, 0xf9, 0x0c, 0xf8, 0x6d, 0x61, 0xad, 0xd4, 0x93, 0x5f, 0x15, 0x97,
	0xaf, 0x78, 0x81, 0x8b, 0x9b, 0xd1, 0xc9, 0x84, 0x34, 0x90, 0xba, 0x41, 0x64, 0xc4, 0xbd, 0xbe,
	0x5d, 0x7b, 0x91, 0x7e, 0xe4, 0x2a, 0x60, 0xcd, 0xda, 0x55, 0x34, 0x6f, 0xfb, 0xe6, 0xde, 0x99,
	0xec, 0x1d, 0x20, 0x00, 0xf3, 0xef, 0xa4, 0x65, 0x9b, 0x14, 0x49, 0x79, 0xa8, 0xc3, 0x0d, 0xd6,
	0xe4, 0x13, 0xab, 0x52, 0xcf, 0xf6, 0xaf, 0x48, 0xca, 0x63, 0x1d, 0x5f, 0x40, 0x93, 0xb7, 0xec,
	0xe9, 0x33, 0xaa, 0x4d, 0x8b, 0xb4, 0x3c, 0x3d, 0xce, 0xb8, 0x4b, 0x30, 0x4a, 0xf0, 0x35, 0x6f,
	0x75, 0x84, 0x9a, 0x2c, 0xc4, 0xcf, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0xac, 0x84, 0x1f,
	0xb8, 0x00, 0x00, 0x00,
}
